# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-18 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 8, 18, 11, 3, 42, 455594))),
            ],
        ),
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 8, 18, 11, 3, 42, 458420))),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_models.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=128)),
                ('views', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 8, 18, 11, 3, 42, 456250))),
                ('answers', models.ManyToManyField(related_name='answers_for_questionn', to='feed_models.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 8, 18, 11, 3, 42, 455073))),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2018, 8, 18, 11, 3, 42, 457833))),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_models.Answer')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_models.Topic'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed_models.Question'),
        ),
    ]
